### ISSUE TITLE
Child posts field on upload_bvas contains a comma with only one entry

### ISSUE THREAD

**Issue by Strongbird** [Sasquire/Idems-Sourcing-Suite#19]
I assume that e621 understands commas between child posts as a separator indicator. However, a new user may misinterpret its default inclusion as an oversight and manually remove it from the "Children" field every time. If possible, I would advise to remove the comma when only one child post is present to prevent requiring an assumption or additional research.

**Comment by Sasquire** [comment]
In fact, the code extracts out groups of numbers from the field. You could use any (non number) separator you desire. But yes, removing the initial comma may help reduce confusion about how that field works.

**Comment by Sasquire** [comment]
The issue is no longer relevant because of the change to the BVAS page.
