### ISSUE TITLE
Clearer indication that files have been successfully downloaded on image_compare

### ISSUE THREAD

**Issue by Strongbird** [Sasquire/Idems-Sourcing-Suite#20]
Currently, image_compare does not give a crystal-clear indicator as to which files are presently loaded. This may yield confusion if a user is working with multiple similar URL fields to determine any discrepancies in visual data. To remedy this, I suggest adding two lines beneath the existing fields:

Source 1: <URL here>
Source 2: <URL here>

The downside of this approach is a reduction in initial visibility of the loaded images. However, I feel that displacing the images slightly to provide a clearer indicator of the specified URLs being successfully loaded is a net positive.

**Comment by Sasquire** [comment]
Implemented in 20cae1c1f1c43ee8c7a599510c808d7a54f66d5e.

On the redesign images being loaded is logged and output to the user.
