### ISSUE TITLE
Option to disable md5 hasher globally or on per-site basis

### ISSUE THREAD

**Issue by Strongbird** [Sasquire/Idems-Sourcing-Suite#21]
I currently do not use the on-site-md5-hasher feature. However, using other aspects of the script, such as image_compare and upload_bvas, requires loading md5 hashes for every site supported (as far as I know). If possible, I would like an easy method for disabling this aspect of the script since it occasionally causes brief hangs on supported websites while loading a page (Firefox, 69.0.1).

**Comment by Sasquire** [comment]
Implemented in 5dd2e20f5f8de359f68307fdca962c248b88d94a.

There was a thought about allowing each site to have its own individual settings for hasher, copy description, and upload buttons, but it was decided against. The reason for not having all three options for every site was a fear that this would be implementing features no one would use and creating too much clutter on the settings page. Instead the current setup of disabling sites or features was chosen.

These settings can be changed at the [extensions page](https://e621.net/extensions).
