### ISSUE TITLE
md5 checksum doesn't work on pixiv.net

### ISSUE THREAD

**Issue by Hentai4me** [Sasquire/Idems-Sourcing-Suite#23]
I'm running latest version of Tampermonkey on Firefox 69 (nice) and the latest Chrome version with both Violentmonkey & Tampermonkey.

On pixiv it used to show bellow each image but now there is no md5 string nor any link to it and when I look into tampermonkey it doesn't show the script running/loaded.

There's a similar issue on at least FA with no md5 link but at least the script is loaded.

**Comment by Hentai4me** [comment]
Don't know though if this is related to Harry.lu IQDB's database being down or if e621.net has done some funky business.

**Comment by Sasquire** [comment]
I am having the same issue, but I am waiting to solve it because I am working on a hopefully better version.

**Comment by Hentai4me** [comment]
I see, I did see it work on 1 image.

**Comment by Sasquire** [comment]
There were a lot of issues with the site redesign and just switching over to the new version solved many of the issues. I refixed pixiv in commit 53c7c595af3f3d269fbbb214fbaac3c98fc1f851.
