### ISSUE TITLE
MD5 checker does not display on FurAffinity "Modern" template

### ISSUE THREAD

**Issue by Strongbird** [Sasquire/Idems-Sourcing-Suite#26]
The sourcing script does not display MD5 checks or the "Upload to e621" button when viewing FA posts with the Modern template enabled.

Example URLs tested by toggling between Classic and Modern under Account Settings :
https://www.furaffinity.net/view/24356189/
https://www.furaffinity.net/view/26348050/

Additional info:
Prior to adjustments for compatibility with the e621 update, MD5s were displayed to the left of the Views/Comments/Favorites/Rating section in the top right of a post page, displacing the text. For the purpose of convenience, retaining placement in the top right would prevent unnecessary page scrolls to check MD5s.

**Comment by Sasquire** [comment]
Solved in commit b00f29d5443fc466dbebe1345b587f515221845f.

Changing selectors was all that was required.
