### ISSUE TITLE
MD5 checker missing line breaks on Inkbunny posts

### ISSUE THREAD

**Issue by Strongbird** [Sasquire/Idems-Sourcing-Suite#27]
The MD5 checker is missing line breaks on Inkbunny posts, causing text to overflow to the next line.

Example post (safe): https://inkbunny.net/s/1844277

**Comment by Sasquire** [comment]
Fixed in commit c63df5baaff7cff83792a4b69584b2828a120273.

Forcing the display rules on the inkbunny post worked. Using `!important` is usually frowned upon but this is a good time to use its power.
