### ISSUE TITLE
Does not load with violentmonkey (on Firefox latest stable v68)

### ISSUE THREAD

**Issue by Hentai4me** [Sasquire/Idems-Sourcing-Suite#3]
From what I can tell violentmonkey does not seem to be able to load either the /extensions/* tools nor give the md5 on the supported sites while tampermonkey does.

**Comment by Sasquire** [comment]
The issue was incorrect match rules to activate the script on specific pages. I have fixed that and then the issues that would have later arisen.

I did not do a full test, but I got it to work on Firefox 68.0.1 with Violentmonkey v2.11.2

Thank you for the bug report.
