### ISSUE TITLE
DeviantArt MD5s re-checked when viewing submissions with several comments, pushing comments down

### ISSUE THREAD

**Issue by The-Polymorphic** [Sasquire/Idems-Sourcing-Suite#32]
When I view comments on DeviantArt when a submission there has received many of them, the sourcing suite treats it as viewing a new page and checks the MD5s of the image again, causing repeated text to appear. This pushes down the comments and the description, making it hard to read them. This is likely because if you scroll down on the page to view the comments, `?comment=1%3A<random numbers>%3A<random numbers>` gets added at the end of the URL. Since the random numbers change depending on what comment you're reading, this means that the URL changes multiple times, triggering multiple checks.

![Working normally](https://user-images.githubusercontent.com/64727240/83347747-1fa7cf80-a2f5-11ea-85ef-1093150b547f.png)
![Scrolling down](https://user-images.githubusercontent.com/64727240/83347746-1f0f3900-a2f5-11ea-8b23-df8903c48398.png)
![Repeated checks](https://user-images.githubusercontent.com/64727240/83347745-1f0f3900-a2f5-11ea-9742-a10fc3ccea28.png)

**Comment by Sasquire** [comment]
Thank you for the bug report. I just solved this in commit 3261598fbb85731d40efd6c14a99328379ee372d (version 1.00042).
