### ISSUE TITLE
Fur Affinity posts not displaying MD5 hashes after image server update

### ISSUE THREAD

**Issue by The-Polymorphic** [Sasquire/Idems-Sourcing-Suite#34]
Fur Affinity posts no longer show the MD5 of posts after the site went independent again and changed the image server URL from `facdn.net` to `furaffinity.net`. I was able to fix this on my end by changing all instances of `facdn.net` to `furaffinity.net`, but the code should be updated in the project proper to reflect that.

**Comment by Sasquire** [comment]
Resolved in commit 9ca7e0b29da433d20c8f1c86b7a7d29e1e7b1636

Versions 1.00046 and 1.00045 should work.
