### ISSUE TITLE
Post BVASer doesn't work on Greasemonkey

### ISSUE THREAD

**Issue by GrippenDynamik** [Sasquire/Idems-Sourcing-Suite#6]
Firefox 69.0
Linux Mint 19.1

When I installed Idems-Sourcing-Suite in Greasemonkey, https://e621.net/extensions/upload_bvas only opened an empty page.

It works perfectly in Tampermonkey.

Switching to Tampermonkey isn't a problem for me, because eSix Extend (my must-have script for e621) works fine in Tampermonkey.
It might be a problem for other people, though, so I'm reporting it.

**Comment by Sasquire** [comment]
I can replicate this problem, but I can not find a solution.

Greasemonkey 4.0 has removed the `GM_getResourceText` function and I can not find a way to replace its functionality.

https://github.com/greasemonkey/greasemonkey/issues/2548

**Comment by Sasquire** [comment]
This should have been solved when I switched over to the new version which is made with browserify. I test the script with firefox and greasemonkey occasionally, but if anything comes up as an issue please make another issue, I'm happy to fix these problems.
